### ISSUE TITLE
receiving "Body hash did not verify" on every DKIM signature

### ISSUE THREAD

**Issue by niftylettuce** [jhermsmeier/node-dkim#7]
The signature hashes are failing to verify 😦

**Comment by jhermsmeier** [comment]
Can you provide some more information? Which version, headers & message if possible, etc..? Are you running it on the raw message, or is it previously modified in any way?

**Comment by niftylettuce** [comment]
I was running on raw message, unmodified.  e.g. an email from Twitch or
Amazon
