### ISSUE TITLE
we should remove X-Google-DKIM-Signature, it's not to RFC standards

### ISSUE THREAD

**Issue by niftylettuce** [jhermsmeier/node-dkim#8]

**Comment by jhermsmeier** [comment]
Other than that it's not defined in an RFC, is it causing any issues, or why would you argue for it to be removed?

**Comment by niftylettuce** [comment]
It's not a real DKIM signature, and no email client parses it as far as I know, anything with `X-` as you know is just extra metadata.

**Comment by jhermsmeier** [comment]
> It's not a real DKIM signature

Last time I checked, it was. What else would it be? If it doesn't verify, that's another issue. If you have a real sample message, and a test case to prove it, I'm happy to look at it, and remove the `X-Google-DKIM` matching, if it checks out.

> and no email client parses it as far as I know

And that's an argument? Most email clients don't even check / verify DKIM signatures. Sorry, but that's just no standard I'm going to measure against.
